# Generated by Django 5.0.6 on 2024-09-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_category_handle_delete_advocate_delete_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='bio',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='handle',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
